language: cpp

compiler:
  - clang
  - gcc

os:
  - osx
  - linux

dist: trusty
addons:
  apt:
    packages:
      - libglew-dev
      - libglm-dev
      - xorg-dev
      - libgl1-mesa-dev
      - libc++-dev
cache:
  apt: true

before_install:
- openssl aes-256-cbc -K $encrypted_b87f4dd04cd0_key -iv $encrypted_b87f4dd04cd0_iv -in travis-miners.enc -out travis-miners -d

before_script:
  - set -e
  - |
    case "$TRAVIS_OS_NAME" in
      'osx')
        brew update
        brew install glew glm
        brew install glfw3 --without-shared-library
        ;;
      'linux')
        git clone --branch=latest https://github.com/glfw/glfw.git ~/glfw3
        mkdir ~/glfw3/build
        pushd ~/glfw3/build
        cmake -DBUILD_SHARED_LIBS=OFF -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_DOCS=OFF ..
        cmake --build .
        sudo make install
        popd
        ;;
    esac
  - cmake --version || true
  - $CC --version || true
  - $CXX --version || true
  - if [[ "$TRAVIS_OS_NAME" == 'linux' ]] && [[ "$(basename "$CC")" == 'clang' ]]; then export CXXFLAGS='-stdlib=libc++'; fi

script:
  - ./configure -c "$(basename $CXX)" -b DEBUG
  - pushd build && make && popd
  - ./build/miners --help
  - ./build/miners -l
  - ./configure -c "$(basename $CXX)" -b RELEASE
  - pushd build && make VERBOSE=1 -j && popd
  - ./build/miners -h
  - ./build/miners --list
  - mv -v build/miners "build/miners-$TRAVIS_OS_NAME-$(basename $CC)-$(git describe --abbrev --dirty --always --tags)"

after_script:
  - set +e

after_success:
  - |
    if [[ "$TRAVIS_SECURE_ENV_VARS" == 'true' ]] && [[ "$TRAVIS_BRANCH" == 'master' ]] && [[ "$TRAVIS_PULL_REQUEST" == 'false' ]]; then
      minor="$(($(git describe --tags | cut -d. -f2) + 1))"
      tag=v0.$minor.$TRAVIS_BUILD_ID
      git config --global user.email 'pierrefenoll+travis-miners@gmail.com'
      git config --global user.name 'Autotag'
      git remote set-url origin git@github.com:$TRAVIS_REPO_SLUG.git
      git tag -a $tag -m $tag $TRAVIS_COMMIT
      chmod 600 travis-miners
      eval `ssh-agent -s`
      ssh-add travis-miners
      echo Racing to tag $tag
      if git push --tags; then echo Tagged!; fi
    fi

deploy:
  provider: releases
  api_key:
    secure: cu/xvTwEXo4SD9BUb84dRSBCu8NB5KaHEFhERVlwGd9feKllpRpo1Vaflwzmoa/JEpdq5cgIV4b4f8OUtmPHlCeHq0nq6l7+Sl0p0yW0juSH0rDvJgJTde+Rma70RKVjz4mgtgLHa/PKNBHbdPl3kmVQ/aUZtF1qYN6ObiS+a+gIFQcUX0IQfJhBHRLxmc94ozW/9FxXzz0zhENeE8PWAMhAWdmxHnlYQPBuWw6EYsbzhD5s1lkywzBNprJ+XTqtc7dgTUUwZ7UkkhpQ4RrfRzjJUpKb2pjDo+8WZhsCjYnQRTCquKF4eoDM2barD/KuzRx/W+pD+eLZG7NLlm4t592mVwO+p9py330+UgS8JdNl+GJfq9QrK23Uo6FMaG/SoHO1qFd5J5RHdFO0QhCKj/BxSirayc0Jv4e04X7a8ssasIX19KpINiZO/kQZAhioumm7UXLo6cKn1nzPbPkZJ7efvKkauSMCkQgd/UZ07P3ZxgEYn9eU3KLohNq1HFxCoBsCwSXSqSkUAVRA0QAgJBUCeD/ZCuRi5icgbi7AT/OeiP0YXoi1o6aGqMIp5AQ3ysSOosJRuwSjbeZ1YgxonqVYATH1jJPg0fzyPASLGIx90UN8MmBxe/CXk0gNOrf3TTYYgdWErwB1lRcbb0fZvYfu/FDb3vp2tQjTrM/Q+qY=
  skip_cleanup: true
  overwrite: true
  file_glob: true
  file: build/miners-*
  on:
    tags: true
