
name: voidstar
version: '1.14.238936273' # just for humans, typically '1.2+git' or '1.3.2'
summary: void* casts files onto 2D/3D colored spaces for your mind blowing needs # 79 char long summary
description: |
  https://github.com/fenollp/voidstar/blob/master/README.md

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  voidstar:
    command: voidstar

parts:
  voidstar:
    plugin: cmake
    source: https://github.com/fenollp/voidstar.git
    stage-packages:
      - libglew-dev
      - libglm-dev
      - libglfw3-dev
