
name: voidstar
version: '1.14.238936273' # just for humans, typically '1.2+git' or '1.3.2'
summary: void* casts files onto 2D/3D colored spaces for your mind blowing needs # 79 char long summary
description: |
  https://github.com/fenollp/voidstar/blob/master/README.md

grade: stable
confinement: strict

apps:
  voidstar:
    command: bin/voidstar
    plugs:
      - opengl  # to access rendering hardware
      - x11  # to create windows
      - home  # to read files in $HOME
      - removable-media  # to read USB keys
      - optical-drive  # to read CDs
      - network  # to read URLs

parts:
  voidstar:
    plugin: cmake
    # source: https://github.com/fenollp/voidstar.git
    source: .
    configflags:
      - -DCMAKE_INSTALL_PREFIX=/bin
    build-packages:
      - libglm-dev
    stage-packages:
      - libglew-dev
      - libglfw3-dev
